env:
  JULIA_VERSION: "1.7.0"
  SLURM_CPUS_PER_TASK: 1
  OPENMPI_VERSION: "4.0.4"
  CUDA_VERSION: "11.2"
  OPENBLAS_NUM_THREADS: 1
  CLIMATEMACHINE_SETTINGS_FIX_RNG_SEED: "true"
  BUILDKITE_COMMIT: "${BUILDKITE_COMMIT}"
  BUILDKITE_BRANCH: "${BUILDKITE_BRANCH}"
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/cpu"

steps:

  # Report to Codecov
  # - plugins:
  #     - joscha/codecov#v2.1.6: ~

  - label: "init environment :computer:"
    key: "init_cpu_env"
    command:
      - "echo $$JULIA_DEPOT_PATH"
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project -e 'using Pkg; Pkg.precompile()'"
      - "julia --project -e 'using Pkg; Pkg.status()'"

      - "julia --project=integration_tests -e 'using Pkg; Pkg.develop(path = \".\")'"
      - "julia --project=integration_tests -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=integration_tests -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=integration_tests -e 'using Pkg; Pkg.status()'"

      - "julia --project=integration_tests integration_tests/download_artifacts.jl"

    agents:
      config: cpu
      queue: central

  - wait


  - label: "Bomex Inv julia_par"
    key: "cpu_bomex_julia_p10"
    command:
      - "julia --color=yes -p 10 --project=integration_tests integration_tests/julia_parallel_test.jl --config Bomex_inversion_test_config.jl"
    artifact_paths:
      - "integration_tests/output/Bomex_inversion_test_config_julia_parallel/*"
    agents:
      config: cpu
      queue: central
      slurm_cpus_per_task: 11

  - label: "Bomex Inv continue"
    key: "cpu_bomex_continue"
    depends_on: "cpu_bomex_julia_p10"
    command:
      - "julia --color=yes -p 10 --project=integration_tests integration_tests/continue_julia_parallel_test.jl --config Bomex_inversion_test_config.jl"
    artifact_paths:
      - "integration_tests/output/Bomex_inversion_test_config_julia_parallel/*"
    agents:
      config: cpu
      queue: central
      slurm_cpus_per_task: 11

  - label: "Bomex SparseInv julia_par"
    key: "cpu_bomex_sparse"
    command:
      - "julia --color=yes -p 10 --project=integration_tests integration_tests/julia_parallel_test.jl --config Bomex_sparseinversion_test_config.jl"
    artifact_paths:
      - "integration_tests/output/Bomex_sparseinversion_test_config_julia_parallel/*"
    agents:
      config: cpu
      queue: central
      slurm_cpus_per_task: 11

  - label: "SCT1 julia parallel"
    key: "cpu_sct1_julia_p10"
    command:
      - "julia --color=yes -p 10 --project=integration_tests integration_tests/julia_parallel_test.jl --config SCT1_integration_test_config.jl"
    artifact_paths:
      - "integration_tests/output/SCT1_integration_test_config_julia_parallel/*"
    agents:
      config: cpu
      queue: central
      slurm_cpus_per_task: 11

  - label: "Heterogeneous batching"
    key: "cpu_het_batch"
    command:
      - "julia --color=yes -p 7 --project=integration_tests integration_tests/julia_parallel_test.jl --config Het_batch_unscented_test_config.jl"
    artifact_paths:
      - "integration_tests/output/Het_batch_unscented_test_config_julia_parallel/*"
    agents:
      config: cpu
      queue: central
      slurm_cpus_per_task: 8
      
  - label: "grid search"
    key: "grid_search_p10"
    command:
      - "julia --color=yes -p 10 --project=integration_tests integration_tests/grid_search_test.jl grid_search_integration_test_config.jl"
    artifact_paths:
      - "integration_tests/output/grid_search/*"
    agents:
      config: cpu
      queue: central
      slurm_cpus_per_task: 11

  - label: "helper_funcs"
    key: "cpu_helper_funcs"
    command:
      - "julia --color=yes --project test/helper_funcs/runtests.jl"
    agents:
      config: cpu
      queue: central

  - label: "DistributionUtils"
    key: "cpu_distributionutils"
    command:
      - "julia --color=yes --project test/DistributionUtils/runtests.jl"
    agents:
      config: cpu
      queue: central

  - label: "LESUtils"
    key: "cpu_lesutils"
    command:
      - "julia --color=yes --project test/LESUtils/runtests.jl"
    agents:
      config: cpu
      queue: central

  - label: "TurbulenceConvectionUtils"
    key: "cpu_turbulenceconvectionutils"
    command:
      - "julia --color=yes --project test/TurbulenceConvectionUtils/runtests.jl"
    agents:
      config: cpu
      queue: central

  - label: "ReferenceModels"
    key: "cpu_referencemodels"
    command:
      - "julia --color=yes --project test/ReferenceModels/runtests.jl"
    agents:
      config: cpu
      queue: central

  - label: "ReferenceStats"
    key: "cpu_referencestats"
    command:
      - "julia --color=yes --project test/ReferenceStats/runtests.jl"
    agents:
      config: cpu
      queue: central

  - label: "Pipeline"
    key: "cpu_pipeline"
    command:
      - "julia --color=yes --project test/Pipeline/runtests.jl"
    agents:
      config: cpu
      queue: central

  - label: "NetCDFIO"
    key: "cpu_netcdfio"
    command:
      - "julia --color=yes --project test/NetCDFIO/runtests.jl"
    agents:
      config: cpu
      queue: central




