env:
  JULIA_VERSION: "1.7.0"
  OPENMPI_VERSION: "4.0.4"
  CUDA_VERSION: "11.2"
  OPENBLAS_NUM_THREADS: 1
  CLIMATEMACHINE_SETTINGS_FIX_RNG_SEED: "true"
  BUILDKITE_COMMIT: "${BUILDKITE_COMMIT}"
  BUILDKITE_BRANCH: "${BUILDKITE_BRANCH}"
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/cpu"

steps:
  - label: "init environment :computer:"
    key: "init_cpu_env"
    command:
      - "echo $$JULIA_DEPOT_PATH"
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project -e 'using Pkg; Pkg.precompile()'"
      - "julia --project -e 'using Pkg; Pkg.status()'"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - wait

  - label: "helper_funcs"
    key: "cpu_helper_funcs"
    command:
      - "julia --color=yes --project test/helper_funcs/runtests.jl"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: "DistributionUtils"
    key: "cpu_distributionutils"
    command:
      - "julia --color=yes --project test/DistributionUtils/runtests.jl"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: "LESUtils"
    key: "cpu_lesutils"
    command:
      - "julia --color=yes --project test/LESUtils/runtests.jl"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: "TurbulenceConvectionUtils"
    key: "cpu_turbulenceconvectionutils"
    command:
      - "julia --color=yes --project test/TurbulenceConvectionUtils/runtests.jl"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: "ReferenceModels"
    key: "cpu_referencemodels"
    command:
      - "julia --color=yes --project test/ReferenceModels/runtests.jl"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: "ReferenceStats"
    key: "cpu_referencestats"
    command:
      - "julia --color=yes --project test/ReferenceStats/runtests.jl"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: "Pipeline"
    key: "cpu_pipeline"
    command:
      - "julia --color=yes --project test/Pipeline/runtests.jl"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: "NetCDFIO"
    key: "cpu_netcdfio"
    command:
      - "julia --color=yes --project test/NetCDFIO/runtests.jl"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: "Calibrate julia parallel"
    key: "cpu_calibrate_julia"
    command:
      - cd experiments/scm_pycles_pipeline/julia_parallel
      - "julia --color=yes --project calibrate.jl --config ../config.jl"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: "Calibrate julia parallel experimental 2"
    key: "cpu_calibrate_julia_experimental2"
    command:
      - cd experiments/scm_pycles_pipeline/julia_parallel_experimental
      - "julia --color=yes -p 2 --project calibrate.jl --config ../config.jl"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 3

  - label: "Calibrate julia parallel experimental 4"
    key: "cpu_calibrate_julia_experimental5"
    command:
      - cd experiments/scm_pycles_pipeline/julia_parallel_experimental
      - "julia --color=yes -p 4 --project calibrate.jl --config ../config.jl"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 5

  - label: "Calibrate julia parallel experimental 8"
    key: "cpu_calibrate_julia_experimental8"
    command:
      - cd experiments/scm_pycles_pipeline/julia_parallel_experimental
      - "julia --color=yes -p 8 --project calibrate.jl --config ../config.jl"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 9

  - label: "Calibrate julia parallel experimental 16"
    key: "cpu_calibrate_julia_experimental16"
    command:
      - cd experiments/scm_pycles_pipeline/julia_parallel_experimental
      - "julia --color=yes -p 16 --project calibrate.jl --config ../config.jl"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 17

